// Automatically generated by MockGen. DO NOT EDIT!
// Source: cluster.go

package mock_teardown

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Cluster interface
type MockCluster struct {
	ctrl     *gomock.Controller
	recorder *_MockClusterRecorder
}

// Recorder for MockCluster (not exported)
type _MockClusterRecorder struct {
	mock *MockCluster
}

func NewMockCluster(ctrl *gomock.Controller) *MockCluster {
	mock := &MockCluster{ctrl: ctrl}
	mock.recorder = &_MockClusterRecorder{mock}
	return mock
}

func (_m *MockCluster) EXPECT() *_MockClusterRecorder {
	return _m.recorder
}

func (_m *MockCluster) Setup() {
	_m.ctrl.Call(_m, "Setup")
}

func (_mr *_MockClusterRecorder) Setup() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Setup")
}

func (_m *MockCluster) Teardown() {
	_m.ctrl.Call(_m, "Teardown")
}

func (_mr *_MockClusterRecorder) Teardown() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Teardown")
}

func (_m *MockCluster) Addresses() []string {
	ret := _m.ctrl.Call(_m, "Addresses")
	ret0, _ := ret[0].([]string)
	return ret0
}

func (_mr *_MockClusterRecorder) Addresses() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Addresses")
}
